# Generated by Django 3.1.5 on 2021-11-12 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20211001_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='p_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.posttype'),
        ),
    ]
